Linear search
kawanaka-s-ts/LinearSearch pull request #1
Opened 2019-02-21 01:32 UTC by kawanaka-s-ts

課題として、線形探索アルゴリズムを作成した。
配列に関して、要素、要素数、添え字（インデックス）がどのようなものか復習できた。
自分のやろうとしていることを、文字として正確に書き出すことの大事さを痛感した。
Rspecの使い方を学ぶ事ができた。

2019-02-21 01:52 UTC, kyakumoto-ts requested changes
```
初期設定
```
伝え忘れたのですが、 `vendor/bundle` の様に外部から取得するリソースはGitHubでは管理しません。
`.gitignore` を利用して管理対象外としてください。

2019-02-21 05:23 UTC, kyakumoto-ts requested changes
```
線形探索アルゴリズム作成

- 配列は要素、添え字、要素数などの情報を持っている
- 添え字を指定してやれば要素を取得する事ができる
```

ファイル名ですが、今回の場合はクラス名をスネークケースにしたものの方が相応しいと思います。

2019-02-21 05:23 UTC, kyakumoto-ts commented on lib/search.rb
> +require "pry"
##### L1

`pry` は debug用ですので、削除しておきましょう。

2019-02-21 05:23 UTC, kyakumoto-ts commented on lib/search.rb
> +  attr_accessor :num, :target
##### L4

`attr_accessor を使用することにより、何ができる様になるのか？` を再度確認してみましょう。

2019-02-21 05:23 UTC, kyakumoto-ts commented on lib/search.rb
> +  def run(num, target)
##### L6

`num` はあまり良い仮引数名とは言えません。
`#run` の第一引数には何を指定する必要があるのか？を考え、適切な名前に変更をしてください。

2019-02-21 05:23 UTC, kyakumoto-ts commented on lib/search.rb
> +    # binding.pry
##### L12

不要なコメントになります。削除しましょう。

2019-02-21 05:23 UTC, kyakumoto-ts commented on lib/search.rb
> +    index = 0
##### L10, L11

`index` という変数を使用するのは良いと思います！
ですが、コメントは正しく説明ができていると言えないです。
もう一度何をやる処理なのかを考えてみてください。

2019-02-21 05:23 UTC, kyakumoto-ts commented on lib/search.rb
> +      if numbers[index] != target
##### L16

L14で何を行なっているかを再度確認してみましょう。

2019-02-21 05:23 UTC, kyakumoto-ts commented on lib/search.rb
> +  p index
##### L23, L24

specに書いた内容と整合性は取れていますでしょうか？

2019-02-21 05:28 UTC, kyakumoto-ts requested changes
要素数を指定するように変更

2019-02-21 05:28 UTC, kyakumoto-ts commented on lib/search.rb
> +  def run(target, num_size)
##### L8 - L10

方針を変えるのであれば、まずテストから直しましょう。
テストしたいことと整合性が取れているかを検討してみましょう。

2019-02-21 05:28 UTC, kyakumoto-ts commented on lib/search.rb
> +    num = (1..num_size)
##### L11

`num` は適切な変数名でしょうか。
```
(1..num_size)
```
の結果が何が変えるのかをもう一度考えてみてください。

2019-02-21 05:30 UTC, kyakumoto-ts commented
https://github.com/kawanaka-s-ts/LinearSearch/pull/1/commits/a70b96e5aa4364e6391ff9695653aa419e96aa0d
https://github.com/kawanaka-s-ts/LinearSearch/pull/1/commits/c4e149de7a632a1751b32453052305aa242af9f2
これらは、本当に初期設定のcommitに含めるのが正しいのでしょうか。

2019-02-21 05:57 UTC, kawanaka-s-ts commented on lib/search.rb
> +  attr_accessor :num, :target
attr_accessor を使用することでインスタンス変数を読み書きできるようになる。

2019-02-21 06:00 UTC, kyakumoto-ts commented on lib/search.rb
> +  attr_accessor :num, :target
@kawanaka-s-ts 
正しい認識です！
それを踏まえて、今回必要かどうかを検討してみてください。

2019-02-21 06:01 UTC, kyakumoto-ts commented on lib/search.rb
> +  attr_accessor :num, :target
>attr_accessor を使用することでインスタンス変数を読み書きできるようになる。

ちょっと説明不足ではあります。

2019-02-21 07:11 UTC, shugo commented on lib/search.rb
> +    # 引数numを配列にする
細かいですが、numは「引数」ではないですね。

2019-02-21 07:11 UTC, shugo commented on lib/search.rb
> +    num = (1..num_size)
探索対象が常に等差数列になっているのが、線形探索の演習としてはちょっと面白くない気もしますね。
探索対象は引数で与えるようにして、もう少し色々な探索対象で試してみてはどうでしょうか。

2019-02-21 07:11 UTC, shugo commented on lib/search.rb
> +    while numbers[index] != target do
doは省略する方が一般的です。

2019-02-21 07:11 UTC, shugo commented on lib/search.rb
> +  p index
pは引数をそのまま返すのでspec自体は通ると思うのですが、意図しているわけではない気がしますね。

値を計算する部品（クラスやメソッド）では表示を行わないようにした方が、テストや修正がしやすいと思います。

2019-02-22 01:11 UTC, kawanaka-s-ts commented on lib/search.rb
> +    while numbers[index] != target do
省略できることを実際に書いてみて確認できました。

2019-02-22 01:12 UTC, kawanaka-s-ts commented on lib/search.rb
> +    # 引数numを配列にする
よく考えたらそうですね…気をつけます

2019-02-22 01:13 UTC, kawanaka-s-ts commented on lib/search.rb
> +require "pry"
確認漏れていました、削除しました。

2019-02-22 01:14 UTC, kawanaka-s-ts commented on lib/search.rb
> +  def run(num, target)
照合する配列という意味で**check_arry**にしてみました。

2019-02-22 01:15 UTC, kawanaka-s-ts commented on lib/search.rb
> +    # binding.pry
削除しました。

2019-02-22 01:17 UTC, kawanaka-s-ts commented on lib/search.rb
> +    index = 0
作成したわけではなく、添え字に0を代入という作業でした。

2019-02-22 01:20 UTC, kawanaka-s-ts commented on lib/search.rb
> +      if numbers[index] != target
これらはL14とL16同じ事なので、L16は必要なかったです。
そのため削除しました。

2019-02-22 01:24 UTC, kawanaka-s-ts commented on lib/search.rb
> +    num = (1..num_size)
探索対象としてランダムな配列の作成は次の課題として作成していきます。
アドバイスありがとうございます。

2019-02-22 01:25 UTC, kawanaka-s-ts commented on lib/search.rb
> +  def run(target, num_size)
この変更は先走ってしまった感じです。
やるべき事がわかってなかった変更でした。

2019-02-22 01:27 UTC, kawanaka-s-ts commented on lib/search.rb
> +  p index
`return`にしてみました。

2019-02-22 01:32 UTC, kawanaka-s-ts commented on lib/search.rb
> +  attr_accessor :num, :target
attr_accessor を使用することで指定したインスタンス変数（今回の場合であれば@num, @target）を読み書きできるようになる。
↑こんな感じでしょうか？

2019-02-22 04:44 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +    return index
##### L14

Rubyのメソッドについて、もう一度確認してみましょう。

```
def one
  1
end

p one #=> ?
```

?には何が入るでしょうか？

2019-02-22 05:01 UTC, kawanaka-s-ts commented on lib/linear_search.rb
> +    return index
１が入ります。(最後に評価された値が返る)
このことから考えると`return`がいらなかったことに気づきました。

2019-02-22 05:32 UTC, shugo commented on lib/linear_search.rb
> +    return index
最後の式がリテラルや変数参照の場合はメソッドの返り値だという意図がわかりやすいですが、他のメッド呼び出しが最後の式だったりすると、値を返す意図がわかりにくいので、必要がなくてもreturnを付けるという流儀もありますね。

Yardなどで仕様を書くならそれも不要ですので、returnをどういう時に使うかはプロジェクト毎に決めていただくのがよいと思います。

2019-02-22 07:19 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +    return index
>他のメッド呼び出しが最後の式だったりすると、値を返す意図がわかりにくいので、必要がなくてもreturnを付けるという流儀もありますね。

なるほどです。
これらについては決めておいた方が良さそうですね。
個人的には、最後が `if | else` の時に `return` が付いていないのは分かりづらいと感じます。
他言語からきたせいなのかなと思ったりはしていますが。。。

2019-02-22 07:42 UTC, kyakumoto-ts commented on lib/search.rb
> +  attr_accessor :num, :target
宣言しなくとも、インスタンス変数への読み書きは可能ですね。
```
class Sample
  def test
    @value = 0
    p @value
  end
end
```

2019-02-22 07:45 UTC, kyakumoto-ts commented on lib/search.rb
> +  attr_accessor :num, :target
ちょっと本題からはずれてしまったのですが、気づいて欲しいのは `必要かどうか？` です。

2019-02-22 07:55 UTC, kawanaka-s-ts commented on lib/search.rb
> +  attr_accessor :num, :target
今回はコードの中で、インスタンス変数を使う場面がなかったので、必要ではなかったと思います。（修正済み）

2019-02-22 08:03 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +  def run(target, check_array, index)
##### L6

indexを外から渡したい理由を考えてみましょう。
外から渡すことで何が起きるでしょうか？

```
p LinearSearch.new.run(3, [0, 3, 6, 2], 3) #=> ?
```

2019-02-22 08:11 UTC, kyakumoto-ts commented on lib/search.rb
> +  def run(num, target)
`check_array` だと、 `これそのものがarrayをチェックする` みたいに感じられます。
色々あると思いますが、 `items` とか `list` とかが使われることが多いと思います。

2019-02-22 08:19 UTC, shugo commented on lib/linear_search.rb
> +    return index
Rubyだとifやcaseも式ですけど、他の言語だと文であることが多いので値を返すという意図がわかりにくいかもしれませんね。

逆にLispから来た人などはreturnを使わない傾向があるように思います。

2019-02-22 08:24 UTC, kawanaka-s-ts commented on lib/linear_search.rb
> +  def run(target, check_array, index)
書かれたように、0以外が渡されると探索の始点がズレてしまいますね…
メソッド内部でindexに0を代入してしまうように修正しました。

2019-02-25 02:10 UTC, kyakumoto-ts commented on lib/search.rb
> +  def run(num, target)
@kawanaka-s-ts 
このコメントについても検討をお願いします。

2019-02-25 02:13 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +    # 添え字に0を代入
##### L6

>添字に0を代入

という表現も、少々違和感を覚えます。

`添字` は `index` と `0` のどちらでしょうか？

2019-02-25 02:15 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +    end
##### L9 - L13

`[0, 1, 2, 3] という配列に対し、4を探して欲しい` とrunメソッドに命令したら、どの様な結果になるでしょうか。

2019-02-25 02:46 UTC, kawanaka-s-ts commented on lib/linear_search.rb
> +    # 添え字に0を代入
添え字は`index`です。

2019-02-25 03:05 UTC, kawanaka-s-ts commented on lib/linear_search.rb
> +    end
見つからないため、無限ループに入ってしまいます。
この問題に関しては、PR#2の方で対策しています。

2019-02-25 05:41 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +      return '見つかりません' if index == check_array.size
##### L9 - L15

L14で行なっている様に、 whileを利用する場合は無限ループにならない様にする対応が必要ですので覚えておいてください。
そのうえで、ここで終了させるということは、これは何条件と言えるでしょうか？

2019-02-25 05:52 UTC, kawanaka-s-ts commented on lib/linear_search.rb
> +      return '見つかりません' if index == check_array.size
ここで終了させるという、「終了条件」といえるかと思います。

2019-02-26 04:16 UTC, kyakumoto-ts requested changes
```
配列にtargetが含まれていない場合に対応
```

2019-02-26 04:16 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +    index = 0
##### L7

余計なスペースが入ってしまった様です。

2019-02-26 04:22 UTC, kawanaka-s-ts commented on lib/linear_search.rb
> +    index = 0
気がつかなかったです…diffを注意深く見る癖をつけます。

2019-02-26 04:23 UTC, kyakumoto-ts requested changes
```
戻り値を変更
```
変数名について、もう一度検討をしてみてください。

2019-02-26 04:23 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +  def run(target, numeric_array)
##### L5

あまり `array` という変数名は使用しないです。
arrayという単語を使用せずに表現するなら何が一番意味が伝わるか？を考えてみてください

2019-02-26 04:23 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +      raise 'targetが数値ではありません'
👍

2019-02-26 04:23 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +    while index < numeric_array.size
👍

2019-02-26 04:23 UTC, kyakumoto-ts commented on lib/linear_search.rb
> +      return index if numeric_array[index] == target
👍

2019-02-26 05:22 UTC, kawanaka-s-ts commented on lib/linear_search.rb
> +  def run(target, numeric_array)
探索される数値というのが一番伝わりやすいかなと考えたので`searched_numerics`に変更してみました。

2019-02-27 00:22 UTC, kyakumoto-ts commented on spec/linear_search_spec.rb
> +    context "numbeersにtargetが含まれていない場合" do
##### L15

スペルミスがありますので、修正をお願いします。

2019-02-27 00:28 UTC, kawanaka-s-ts commented on spec/linear_search_spec.rb
> +    context "numbeersにtargetが含まれていない場合" do
修正しました。

2019-02-27 00:31 UTC, kyakumoto-ts approved these changes
LGTM 👍

2019-02-27 00:42 UTC, merged